In [3]:
pip install selenium

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.25.8)
Note: you may need to restart the kernel to use updated packages.

In [190]:
from selenium import webdriver

import time
from bs4 import BeautifulSoup
from selenium.webdriver.common.keys import Keys

In [223]:
# 야후 파이낸스 오픈
chrome = webdriver.Chrome('chromedriver.exe')
driver = chrome.get("https://finance.yahoo.com/")
# 로그인
sign_btn = chrome.find_element_by_css_selector('#header-signin-link') 
sign_btn.click()
time.sleep(1)

In [224]:
# ID/PW 입력   
id_box = chrome.find_element_by_css_selector('#login-username')
id_box.send_keys("richard@hoztec.com")
time.sleep(1)
id_box.send_keys(Keys.ENTER)
time.sleep(1)
psw_box = chrome.find_element_by_css_selector('#login-passwd')
psw_box.send_keys("click3801!")
time.sleep(1)
psw_box.send_keys(Keys.ENTER)

In [225]:
# 검색
input_box = chrome.find_element_by_css_selector('#yfin-usr-qry')
input_box.send_keys("005930.KS")
time.sleep(1)
input_box.send_keys(Keys.ENTER)

In [226]:
# finance 클릭
fnc_btn = chrome.find_element_by_css_selector('#quote-nav > ul > li:nth-child(7) > a')
fnc_btn.click()

In [227]:
# quarterly 클릭
qt_btn = chrome.find_element_by_css_selector('#Col1-1-Financials-Proxy > section > div.Mt\(18px\).Mb\(15px\) > div.Fl\(end\).smartphone_Fl\(n\).IbBox.smartphone_My\(10px\).smartphone_D\(b\) > button > div > span')
qt_btn.click()

In [228]:
# expand all 클릭
exp_btn = chrome.find_element_by_css_selector('#Col1-1-Financials-Proxy > section > div.Mb\(10px\) > button > div > span')
exp_btn.click()

In [197]:
# Balance_sheet 클릭
BS_btn = chrome.find_element_by_css_selector("#Col1-1-Financials-Proxy > section > div.Mt\(18px\).Mb\(15px\) > div:nth-child(1) > div > a:nth-child(2) > div > span")
BS_btn.click()

In [198]:
# quarterly 클릭
qt_btn = chrome.find_element_by_css_selector('#Col1-1-Financials-Proxy > section > div.Mt\(18px\).Mb\(15px\) > div.Fl\(end\).smartphone_Fl\(n\).IbBox.smartphone_My\(10px\).smartphone_D\(b\) > button > div > span')
qt_btn.click()

In [207]:
# CashFlow 클릭
CF_btn = chrome.find_element_by_css_selector("#Col1-1-Financials-Proxy > section > div.Mt\(18px\).Mb\(15px\) > div:nth-child(1) > div > a:nth-child(3) > div > span")
CF_btn.click()

In [208]:
# quarterly 클릭
qt_btn = chrome.find_element_by_css_selector('#Col1-1-Financials-Proxy > section > div.Mt\(18px\).Mb\(15px\) > div.Fl\(end\).smartphone_Fl\(n\).IbBox.smartphone_My\(10px\).smartphone_D\(b\) > button > div > span')
qt_btn.click()

In [229]:
import string

In [230]:
chart = chrome.find_element_by_css_selector("#Main")  #Col1-1-Financials-Proxy  
chart_data = chart.text

In [231]:
chart_data

'Show:Income StatementBalance SheetCash Flow\nAnnualQuarterly\nDownload\nIncome Statement\nCollapse All\nAll numbers in thousands\nBreakdown\nTTM12/30/20199/29/20196/29/20193/30/201912/30/20189/29/20186/29/20183/30/201812/30/20179/29/20176/29/20173/30/201712/30/20169/29/20166/29/20163/30/201612/30/20159/29/20156/29/20153/30/201512/30/20149/29/20146/29/20143/30/201412/30/20139/29/20136/29/20133/30/201312/30/20129/29/20126/29/20123/30/201212/30/20119/29/20116/29/20113/30/201112/30/20109/29/20106/29/20103/30/2010\nTotal Revenue\n230,400,881,000 59,884,760,000 62,003,471,000 56,127,104,000 52,385,546,000 59,265,050,000 65,459,993,000 58,482,658,000 60,563,714,000 65,978,412,000 62,048,901,000 61,000,537,000 50,547,526,000 53,331,740,000 47,815,633,000 50,937,120,000 49,782,252,000 53,315,453,000 51,682,572,000 48,537,539,000 47,117,918,000 52,730,122,000 47,447,310,000 52,353,229,000 53,675,326,000 59,276,625,000 59,083,499,000 57,464,448,000 52,868,095,000 56,058,847,000 52,177,270,000 47,596,979,000 45,270,517,000 47,303,935,228 41,273,965,000 39,438,854,000 36,985,017,000 41,871,078,781 40,229,261,000 37,891,918,000 34,638,070,000\nOperating Revenue\n230,400,881,000 59,884,760,000 62,003,471,000 56,127,104,000 52,385,546,000 59,265,050,000 65,459,993,000 58,482,658,000 60,563,714,000 65,978,412,000 62,048,901,000 61,000,537,000 50,547,526,000 53,331,740,000 47,815,633,000 50,937,120,000 49,782,252,000 53,315,453,000 51,682,572,000 48,537,539,000 47,117,918,000 52,730,122,000 47,447,310,000 52,353,229,000 53,675,326,000 59,276,625,000 59,083,499,000 57,464,448,000 52,868,095,000 56,058,847,000 52,177,270,000 47,596,979,000 45,270,517,000 47,303,935,228 41,273,965,000 39,438,854,000 36,985,017,000 41,871,078,781 40,229,261,000 37,891,918,000 34,638,070,000\nCost of Revenue\n147,239,549,000 38,554,523,000 39,993,890,000 35,944,684,000 32,746,452,000 34,015,984,000 35,194,358,000 31,274,597,000 31,909,472,000 35,731,116,000 33,004,119,000 32,399,829,000 28,155,597,000 30,883,483,000 29,411,256,000 29,609,118,000 30,373,858,000 33,961,680,000 31,609,452,000 28,955,599,000 28,955,387,000 33,846,068,000 30,711,398,000 31,671,819,000 32,049,515,000 36,447,915,000 35,527,620,000 34,341,419,000 31,379,355,000 34,552,747,000 31,989,604,000 29,971,206,000 30,138,374,000 31,509,304,969 27,754,250,000 26,827,122,000 26,054,443,000 29,115,545,033 26,017,008,000 24,525,662,000 23,008,609,000\nGross Profit\n83,161,332,000 21,330,237,000 22,009,581,000 20,182,420,000 19,639,094,000 25,249,066,000 30,265,635,000 27,208,061,000 28,654,242,000 30,247,296,000 29,044,782,000 28,600,708,000 22,391,929,000 22,448,257,000 18,404,377,000 21,328,002,000 19,408,394,000 19,353,773,000 20,073,120,000 19,581,940,000 18,162,531,000 18,884,054,000 16,735,912,000 20,681,410,000 21,625,811,000 22,828,710,000 23,555,879,000 23,123,029,000 21,488,740,000 21,506,100,000 20,187,666,000 17,625,773,000 15,132,143,000 15,794,630,259 13,519,715,000 12,611,732,000 10,930,574,000 12,755,533,748 14,212,253,000 13,366,256,000 11,629,461,000\nOperating Expense\n55,392,823,000 14,169,967,000 14,231,689,000 13,585,355,000 13,405,812,000 14,448,467,000 12,690,770,000 12,339,026,000 13,012,072,000 15,100,325,000 14,511,623,000 14,534,161,000 12,493,568,000 13,227,436,000 13,204,288,000 13,184,052,000 12,732,582,000 13,211,008,000 12,679,747,000 12,684,003,000 12,183,164,000 13,595,627,000 12,675,390,000 13,494,087,000 13,137,012,000 14,517,432,000 13,392,285,000 13,592,346,000 12,709,282,000 12,668,813,000 12,126,332,000 10,923,349,000 9,314,041,000 9,088,951,621 9,261,571,000 8,835,074,000 8,094,589,000 9,287,789,582 9,304,181,000 8,265,494,000 7,515,991,000\nSelling General and Administrative\n27,022,180,000 7,212,126,000 6,977,331,000 6,467,798,000 6,364,925,000 7,178,144,000 6,230,631,000 6,041,156,000 6,787,239,000 8,743,250,000 8,259,109,000 8,353,939,000 6,793,984,000 7,870,911,000 8,013,945,000 7,991,241,000 7,382,803,000 7,943,451,000 7,578,841,000 7,717,021,000 7,003,970,000 8,324,897,000 7,686,507,000 8,162,354,000 7,757,479,000 8,669,128,000 8,121,265,000 8,575,872,000 7,775,732,000 7,877,401,000 7,846,460,000 4,529,526,000 3,170,688,000 1,832,327,556 3,488,329,000 3,305,026,000 2,795,357,000 -2,068,437,900 3,864,279,000 3,356,703,000 2,778,937,000\nGeneral & Administrative Expense\n8,140,819,000 2,383,303,000 2,072,825,000 1,846,504,000 1,838,187,000 1,893,071,000 1,422,861,000 1,715,487,000 1,887,359,000 2,169,572,000 1,956,889,000 2,133,404,000 1,971,551,000 2,373,011,000 2,239,060,000 2,149,008,000 1,647,952,000 1,854,014,000 1,619,536,000 1,864,340,000 2,078,177,000 2,136,499,000 1,947,258,000 1,979,474,000 2,101,557,000 2,129,214,000 1,968,862,000 2,009,157,000 1,796,095,000 1,453,436,000 1,782,426,000 - - - - - - - - - -\nSelling & Marketing Expense\n18,881,361,000 4,828,823,000 4,904,506,000 4,621,294,000 4,526,738,000 5,285,073,000 4,807,770,000 4,325,669,000 4,899,880,000 6,573,678,000 6,302,220,000 6,220,535,000 4,822,433,000 5,497,900,000 5,774,885,000 5,842,233,000 5,734,851,000 6,089,437,000 5,959,305,000 5,852,681,000 4,925,793,000 6,188,398,000 5,739,249,000 6,182,880,000 5,655,922,000 6,539,914,000 6,152,403,000 6,566,715,000 5,979,637,000 6,423,965,000 6,064,034,000 4,529,526,000 3,170,688,000 1,832,327,556 3,488,329,000 3,305,026,000 2,795,357,000 -2,068,437,900 3,864,279,000 3,356,703,000 2,778,937,000\nResearch & Development\n19,907,236,000 4,919,222,000 5,133,014,000 4,952,418,000 4,902,582,000 5,240,471,000 4,519,999,000 4,368,968,000 4,224,642,000 4,433,424,000 4,181,831,000 3,970,405,000 3,769,952,000 3,539,745,000 3,506,418,000 3,498,701,000 3,566,517,000 3,462,980,000 3,415,927,000 3,335,547,000 3,491,241,000 3,652,305,000 3,339,685,000 3,702,672,000 3,690,844,000 3,793,543,000 3,659,594,000 3,541,179,000 3,325,086,000 2,955,874,000 2,975,618,000 2,872,922,000 2,728,381,000 2,742,450,878 2,429,192,000 2,464,123,000 2,344,075,000 2,427,437,271 2,313,368,000 2,305,682,000 2,052,865,000\nOther Operating Expenses\n- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 2,697,455,000 2,432,187,000 6,318,247,427 2,471,311,000 2,276,766,000 2,093,681,000 10,070,245,279 2,302,806,000 2,111,128,000 2,030,601,000\nOperating Income\n27,768,509,000 7,160,270,000 7,777,892,000 6,597,065,000 6,233,282,000 10,800,599,000 17,574,865,000 14,869,035,000 15,642,170,000 15,146,971,000 14,533,159,000 14,066,547,000 9,898,361,000 9,220,821,000 5,200,089,000 8,143,950,000 6,675,812,000 6,142,765,000 7,393,373,000 6,897,937,000 5,979,367,000 5,288,427,000 4,060,522,000 7,187,323,000 8,488,799,000 8,311,278,000 10,163,594,000 9,530,683,000 8,779,458,000 8,837,287,000 8,061,334,000 6,702,424,000 5,818,102,000 6,705,678,638 4,258,144,000 3,776,658,000 2,835,985,000 3,467,744,166 4,908,072,000 5,100,762,000 4,113,470,000\nNet Non Operating Interest Income Expense\n1,973,668,000 483,532,000 510,506,000 491,681,000 487,949,000 477,634,000 426,735,000 403,071,000 315,082,000 246,897,000 259,399,000 200,309,000 252,216,000 232,295,000 243,865,000 213,827,000 226,500,000 231,332,000 240,297,000 237,661,000 275,356,000 339,711,000 325,789,000 299,813,000 275,108,000 274,936,000 239,379,000 168,503,000 159,133,000 104,207,000 75,611,000 36,266,000 30,341,000 -57,446,183 143,696,000 -21,746,000 -6,439,000 19,705,125 -92,319,000 48,596,000 -451,000\nInterest Income Non Operating\n2,660,024,000 642,915,000 682,799,000 672,300,000 662,010,000 670,006,000 616,374,000 559,454,000 451,305,000 431,707,000 420,785,000 361,125,000 400,606,000 387,418,000 392,170,000 331,749,000 392,981,000 446,472,000 445,531,000 426,880,000 442,274,000 490,106,000 480,149,000 445,443,000 417,663,000 397,364,000 371,736,000 299,511,000 282,998,000 242,892,000 223,904,000 192,917,000 185,718,000 209,326,709 177,799,000 165,216,000 149,856,000 156,731,979 135,557,000 124,490,000 139,844,000\nInterest Expense Non Operating\n686,356,000 159,383,000 172,293,000 180,619,000 174,061,000 192,372,000 189,639,000 156,383,000 136,223,000 184,810,000 161,386,000 160,816,000 148,390,000 155,123,000 148,305,000 117,922,000 166,481,000 215,140,000 205,234,000 189,219,000 166,918,000 150,395,000 154,360,000 145,630,000 142,555,000 122,428,000 132,357,000 131,008,000 123,865,000 138,685,000 148,293,000 76,679,000 155,377,000 189,577,893 168,167,000 148,131,000 138,257,000 174,601,855 154,199,000 122,745,000 129,546,000\nTotal Other Finance Cost\n- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 79,972,000 - - -134,064,000 38,831,000 18,038,000 - 73,677,000 -46,851,000 10,749,000\nPretax Income\n30,432,189,000 7,719,119,000 8,620,728,000 7,179,364,000 6,912,978,000 11,607,871,000 17,969,344,000 15,406,836,000 16,175,907,000 16,704,386,000 14,914,740,000 14,412,265,000 10,164,576,000 9,548,506,000 5,970,702,000 8,071,959,000 7,122,485,000 4,724,209,000 7,390,119,000 7,628,024,000 6,218,643,000 5,594,087,000 4,846,871,000 7,785,106,000 9,648,970,000 9,251,857,000 10,239,157,000 9,827,828,000 9,045,437,000 8,532,310,000 8,302,387,000 6,730,055,000 6,350,265,000 5,474,456,990 4,132,214,000 4,164,585,000 3,387,759,000 3,618,024,365 5,423,710,000 5,314,019,000 4,972,903,000\nTax Provision\n8,693,324,000 2,492,079,000 2,333,064,000 1,998,788,000 1,869,393,000 3,145,685,000 4,818,629,000 4,363,424,000 4,487,363,000 4,449,255,000 3,721,329,000 3,358,414,000 2,480,222,000 2,460,465,000 1,432,847,000 2,224,566,000 1,869,682,000 1,500,736,000 1,931,560,000 1,875,727,000 1,592,828,000 247,296,000 624,526,000 1,534,325,000 2,074,529,000 1,950,581,000 1,994,421,000 2,054,017,000 1,890,496,000 1,493,833,000 1,737,460,000 1,536,635,000 1,301,804,000 1,473,201,509 690,504,000 658,221,000 603,021,000 197,610,408 968,284,000 1,037,104,000 979,133,000\nNet Income Common Stockholders\n18,899,137,000 4,593,935,000 5,365,454,000 4,450,996,000 4,488,752,000 7,320,213,000 11,396,510,000 9,651,206,000 11,611,833,000 12,016,324,000 11,039,771,000 10,799,942,000 7,488,532,000 6,917,181,000 4,408,790,000 5,826,178,000 5,263,506,000 3,242,467,000 5,306,104,000 5,626,734,000 4,519,323,000 5,285,891,000 4,135,422,000 6,176,506,000 7,484,680,000 7,219,744,000 8,049,537,000 7,575,016,000 6,976,918,000 6,850,567,000 6,424,872,000 5,049,042,000 4,860,894,000 4,262,309,481 3,300,157,000 3,456,956,000 2,714,645,000 3,299,525,359 4,310,375,000 4,172,692,000 4,016,443,000\nNet Income\n21,505,054,000 5,227,995,000 6,105,039,000 5,064,530,000 5,107,490,000 8,330,069,000 12,967,428,000 10,981,547,000 11,611,833,000 12,016,324,000 11,039,771,000 10,799,942,000 7,488,532,000 6,917,181,000 4,408,790,000 5,826,178,000 5,263,506,000 3,242,467,000 5,306,104,000 5,626,734,000 4,519,323,000 5,285,891,000 4,135,422,000 6,176,506,000 7,484,680,000 7,219,744,000 8,049,537,000 7,575,016,000 6,976,918,000 6,850,567,000 6,424,872,000 5,049,042,000 4,860,894,000 4,262,309,481 3,300,157,000 3,456,956,000 2,714,645,000 3,299,525,359 4,310,375,000 4,172,692,000 4,016,443,000\nNet Income Including Non-Controlling Interests\n21,738,865,000 5,227,040,000 6,287,664,000 5,180,576,000 5,043,585,000 8,462,186,000 13,150,715,000 11,043,412,000 11,688,544,000 12,255,131,000 11,193,411,000 11,053,851,000 7,684,354,000 7,088,041,000 4,537,855,000 5,847,393,000 5,252,803,000 3,223,473,000 5,458,559,000 5,752,297,000 4,625,815,000 5,346,791,000 4,222,345,000 6,250,781,000 7,574,441,000 7,301,276,000 8,244,736,000 7,773,811,000 7,154,941,000 7,038,477,000 6,564,927,000 5,193,420,000 5,048,461,000 4,001,255,481 3,441,710,000 3,506,364,000 2,784,738,000 3,420,413,957 4,455,426,000 4,276,915,000 3,993,770,000\nNet Income Continuous Operations\n21,738,865,000 5,227,040,000 6,287,664,000 5,180,576,000 5,043,585,000 8,462,186,000 13,150,715,000 11,043,412,000 11,688,544,000 12,255,131,000 11,193,411,000 11,053,851,000 7,684,354,000 7,088,041,000 4,537,855,000 5,847,393,000 5,252,803,000 3,223,473,000 5,458,559,000 5,752,297,000 4,625,815,000 5,346,791,000 4,222,345,000 6,250,781,000 7,574,441,000 7,301,276,000 8,244,736,000 7,773,811,000 7,154,941,000 7,038,477,000 6,564,927,000 5,193,420,000 5,048,461,000 4,001,255,481 3,441,710,000 3,506,364,000 2,784,738,000 3,420,413,957 4,455,426,000 4,276,915,000 3,993,770,000\nMinority Interests\n-233,811,000 955,000 -182,625,000 -116,046,000 63,905,000 -132,117,000 -183,287,000 -61,865,000 -76,711,000 -238,807,000 -153,640,000 -253,909,000 -195,822,000 -170,860,000 -129,065,000 -21,215,000 10,703,000 18,994,000 -152,455,000 -125,563,000 -106,492,000 -60,900,000 -86,923,000 -74,275,000 -89,761,000 -81,532,000 -195,199,000 -198,795,000 -178,023,000 -187,910,000 -140,055,000 -144,378,000 -187,567,000 - -141,553,000 -49,408,000 -70,093,000 -120,888,598 -145,051,000 -104,223,000 22,673,000\nPreferred Stock Dividends\n2,605,917,000 634,060,000 739,585,000 613,534,000 618,738,000 1,009,856,000 1,570,918,000 1,330,341,000 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\nOtherunder Preferred Stock Dividend\n0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\nDiluted NI Available to Com Stockholders\n18,899,137,000 4,593,935,000 5,365,454,000 4,450,996,000 4,488,752,000 7,320,213,000 11,396,510,000 9,651,206,000 11,611,833,000 12,016,324,000 11,039,771,000 10,799,942,000 7,488,532,000 6,917,181,000 4,408,790,000 5,826,178,000 5,263,506,000 3,242,467,000 5,306,104,000 5,626,734,000 4,519,323,000 5,285,891,000 4,135,422,000 6,176,506,000 7,484,680,000 7,219,744,000 8,049,537,000 7,575,016,000 6,976,918,000 6,850,567,000 6,424,872,000 5,049,042,000 4,860,894,000 4,262,309,481 3,300,157,000 3,456,956,000 2,714,645,000 3,299,525,359 4,310,375,000 4,172,692,000 4,016,443,000\nBasic EPS\n- - 0.899 0.7456 0.752 - 1.909 1.617 1.7087 - 1.607 1.5604 1.0731 - 0.6261 0.8181 0.7271 - 0.7126 0.7557 0.6062 - 0.5484 0.8191 0.9928 - 0.0011 1.0051 0.9258 - 0 0.6704 0.6468 - 0.44 0.4604 0.3566 - 0.5768 0.5587 0.5421\nDiluted EPS\n- - 0.899 0.7456 0.752 - 1.909 1.617 1.7087 - 1.607 1.5604 1.0731 - 0.6261 0.8181 0.7271 - 0.7126 0.7556 0.6062 - 0.5484 0.819 0.9927 - 0.0011 1.0047 0.9255 - 0 0.6699 0.6463 - 0.4394 0.4594 0.3559 - 0.5745 0.5563 0.5393\nBasic Average Shares\n- - 5,969,783 5,969,783 5,969,783 - 5,969,783 5,969,783 6,796,000 - 6,871,650 6,923,850 6,981,200 - 7,045,300 7,125,600 7,245,300 - 7,445,850 7,445,850 7,454,350 - 7,540,850 7,540,700 7,538,850 - 7,536,700 7,536,500 7,535,750 - 7,531,400 7,530,300 7,515,000 - 7,500,800 7,499,750 7,494,300 - 7,471,950 7,468,550 7,409,500\nDiluted Average Shares\n- - 5,969,783 5,969,783 5,969,783 - 5,969,783 5,969,783 6,796,000 - 6,871,650 6,923,850 6,981,200 - 7,045,300 7,125,600 7,245,300 - 7,445,950 7,445,950 7,454,500 - 7,540,950 7,540,900 7,539,650 - 7,539,150 7,539,250 7,538,600 - 7,536,600 7,536,400 7,520,900 - 7,511,200 7,524,282 7,508,350 - 7,498,100 7,500,525 7,442,700\nTotal Operating Income as Reported\n27,768,509,000 7,160,270,000 7,777,892,000 6,597,065,000 6,233,282,000 10,800,599,000 17,574,865,000 14,869,035,000 15,642,170,000 15,146,971,000 14,533,159,000 14,066,547,000 9,898,361,000 9,220,821,000 5,200,089,000 8,143,950,000 6,675,812,000 6,142,765,000 7,393,373,000 6,897,937,000 5,979,367,000 5,288,427,000 4,060,522,000 7,187,323,000 8,488,799,000 8,311,278,000 10,163,594,000 9,530,683,000 8,779,458,000 8,837,287,000 8,061,334,000 6,724,113,000 5,850,447,000 5,296,404,577 4,252,896,000 3,751,880,000 2,948,536,000 3,012,299,355 4,864,413,000 5,014,212,000 4,405,612,000\nTotal Expenses\n202,632,372,000 52,724,490,000 54,225,579,000 49,530,039,000 46,152,264,000 48,464,451,000 47,885,128,000 43,613,623,000 44,921,544,000 50,831,441,000 47,515,742,000 46,933,990,000 40,649,165,000 44,110,919,000 42,615,544,000 42,793,170,000 43,106,440,000 47,172,688,000 44,289,199,000 41,639,602,000 41,138,551,000 47,441,695,000 43,386,788,000 45,165,906,000 45,186,527,000 50,965,347,000 48,919,905,000 47,933,765,000 44,088,637,000 47,221,560,000 44,115,936,000 40,894,555,000 39,452,415,000 40,598,256,590 37,015,821,000 35,662,196,000 34,149,032,000 38,403,334,615 35,321,189,000 32,791,156,000 30,524,600,000\nNet Income from Continuing & Discontinued Operation\n21,505,054,000 5,227,995,000 6,105,039,000 5,064,530,000 5,107,490,000 8,330,069,000 12,967,428,000 10,981,547,000 11,611,833,000 12,016,324,000 11,039,771,000 10,799,942,000 7,488,532,000 6,917,181,000 4,408,790,000 5,826,178,000 5,263,506,000 3,242,467,000 5,306,104,000 5,626,734,000 4,519,323,000 5,285,891,000 4,135,422,000 6,176,506,000 7,484,680,000 7,219,744,000 8,049,537,000 7,575,016,000 6,976,918,000 6,850,567,000 6,424,872,000 5,049,042,000 4,860,894,000 4,262,309,481 3,300,157,000 3,456,956,000 2,714,645,000 3,299,525,359 4,310,375,000 4,172,692,000 4,016,443,000\nNormalized Income\n21,359,049,769 5,256,017,028 6,001,698,080 5,042,957,267 5,053,361,574 8,234,365,337 12,994,792,292 10,813,460,567 11,449,285,248 12,136,433,834 11,053,829,989 10,806,238,100 7,476,650,049 6,573,573,239 3,830,511,039 6,012,835,527 5,004,571,951 4,716,772,878 5,241,282,624 5,409,494,979 4,472,990,784 5,293,055,627 4,124,376,707 6,123,543,296 8,004,126,244 6,552,378,750 8,058,532,071 7,606,099,132 7,089,011,406 7,432,752,132 6,450,713,770 5,008,953,447 4,986,999,293 4,868,437,972 3,324,518,414 3,477,817,787 2,663,323,428 3,641,824,299 4,365,935,260 4,242,350,575 3,819,563,083\nInterest Income\n2,660,024,000 642,915,000 682,799,000 672,300,000 662,010,000 670,006,000 616,374,000 559,454,000 451,305,000 431,707,000 420,785,000 361,125,000 400,606,000 387,418,000 392,170,000 331,749,000 392,981,000 446,472,000 445,531,000 426,880,000 442,274,000 490,106,000 480,149,000 445,443,000 417,663,000 397,364,000 371,736,000 299,511,000 282,998,000 242,892,000 223,904,000 192,917,000 185,718,000 209,326,709 177,799,000 165,216,000 149,856,000 156,731,979 135,557,000 124,490,000 139,844,000\nInterest Expense\n686,356,000 159,383,000 172,293,000 180,619,000 174,061,000 192,372,000 189,639,000 156,383,000 136,223,000 184,810,000 161,386,000 160,816,000 148,390,000 155,123,000 148,305,000 117,922,000 166,481,000 215,140,000 205,234,000 189,219,000 166,918,000 150,395,000 154,360,000 145,630,000 142,555,000 122,428,000 132,357,000 131,008,000 123,865,000 138,685,000 148,293,000 76,679,000 155,377,000 189,577,893 168,167,000 148,131,000 138,257,000 174,601,855 154,199,000 122,745,000 129,546,000\nNet Interest Income\n1,973,668,000 483,532,000 510,506,000 491,681,000 487,949,000 477,634,000 426,735,000 403,071,000 315,082,000 246,897,000 259,399,000 200,309,000 252,216,000 232,295,000 243,865,000 213,827,000 226,500,000 231,332,000 240,297,000 237,661,000 275,356,000 339,711,000 325,789,000 299,813,000 275,108,000 274,936,000 239,379,000 168,503,000 159,133,000 104,207,000 75,611,000 36,266,000 30,341,000 -57,446,183 143,696,000 -21,746,000 -6,439,000 19,705,125 -92,319,000 48,596,000 -451,000\nEBIT\n31,118,545,000 7,878,502,000 8,793,021,000 7,359,983,000 7,087,039,000 11,800,243,000 18,158,983,000 15,563,219,000 16,312,130,000 16,889,196,000 15,076,126,000 14,573,081,000 10,312,966,000 9,703,629,000 6,119,007,000 8,189,881,000 7,288,966,000 4,939,349,000 7,595,353,000 7,817,243,000 6,385,561,000 5,744,482,000 5,001,231,000 7,930,736,000 9,791,525,000 9,374,285,000 10,371,514,000 9,958,836,000 9,169,302,000 8,670,995,000 8,450,680,000 6,806,734,000 6,505,642,000 5,664,034,883 4,300,381,000 4,312,716,000 3,526,016,000 3,792,626,220 5,577,909,000 5,436,764,000 5,102,449,000\nEBITDA\n60,716,183,000 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\nReconciled Cost of Revenue\n147,239,549,000 38,554,523,000 39,993,890,000 35,944,684,000 32,746,452,000 34,015,984,000 35,194,358,000 31,274,597,000 31,909,472,000 35,731,116,000 33,004,119,000 32,399,829,000 28,155,597,000 30,883,483,000 29,411,256,000 29,609,118,000 30,373,858,000 33,961,680,000 31,609,452,000 28,955,599,000 28,955,387,000 33,846,068,000 30,711,398,000 31,671,819,000 32,049,515,000 36,447,915,000 35,527,620,000 34,341,419,000 31,379,355,000 34,552,

In [232]:
chart_splt = chart_data.split('\n')

In [238]:
gets={}
for x in range(0,len(chart_splt),2):
    gets[chart_splt[x]]=chart_splt[x+1]

In [241]:
df=pd.DataFrame(gets)
df

ValueError: If using all scalar values, you must pass an index

In [180]:
Brkdwn_data = gets["Breakdown"]
Brkdwn_data_splt = Brkdwn_data.split("\/")
Brkdwn_data_splt

['TTM12/30/20199/29/20196/29/20193/30/201912/30/20189/29/20186/29/20183/30/201812/30/20179/29/20176/29/20173/30/201712/30/20169/29/20166/29/20163/30/201612/30/20159/29/20156/29/20153/30/201512/30/20149/29/20146/29/20143/30/201412/30/20139/29/20136/29/20133/30/201312/30/20129/29/20126/29/20123/30/201212/30/20119/29/20116/29/20113/30/201112/30/20109/29/20106/29/20103/30/2010']

In [179]:
nt_icm_data = gets["Net Income"]
nt_icm_data_splt = nt_icm_data.split("\/")
nt_icm_data_splt

['21,505,054,000 5,227,995,000 6,105,039,000 5,064,530,000 5,107,490,000 8,330,069,000 12,967,428,000 10,981,547,000 11,611,833,000 12,016,324,000 11,039,771,000 10,799,942,000 7,488,532,000 6,917,181,000 4,408,790,000 5,826,178,000 5,263,506,000 3,242,467,000 5,306,104,000 5,626,734,000 4,519,323,000 5,285,891,000 4,135,422,000 6,176,506,000 7,484,680,000 7,219,744,000 8,049,537,000 7,575,016,000 6,976,918,000 6,850,567,000 6,424,872,000 5,049,042,000 4,860,894,000 4,262,309,481 3,300,157,000 3,456,956,000 2,714,645,000 3,299,525,359 4,310,375,000 4,172,692,000 4,016,443,000']

In [185]:
tt_rvn_data = gets["Total Revenue"]
tt_rvn_data_splt = tt_rvn_data.split("\/")
tt_rvn_data_splt

['230,400,881,000 59,884,760,000 62,003,471,000 56,127,104,000 52,385,546,000 59,265,050,000 65,459,993,000 58,482,658,000 60,563,714,000 65,978,412,000 62,048,901,000 61,000,537,000 50,547,526,000 53,331,740,000 47,815,633,000 50,937,120,000 49,782,252,000 53,315,453,000 51,682,572,000 48,537,539,000 47,117,918,000 52,730,122,000 47,447,310,000 52,353,229,000 53,675,326,000 59,276,625,000 59,083,499,000 57,464,448,000 52,868,095,000 56,058,847,000 52,177,270,000 47,596,979,000 45,270,517,000 47,303,935,228 41,273,965,000 39,438,854,000 36,985,017,000 41,871,078,781 40,229,261,000 37,891,918,000 34,638,070,000']

In [188]:
nrmlz_ebitda_data = gets["Normalized EBITDA"]
nrmlz_ebitda_data_splt = nrmlz_ebitda_data.split("\/")
nrmlz_ebitda_data_splt

['60,511,792,000 16,663,718,000 15,518,895,000 14,220,787,000 14,108,392,000 18,561,274,000 25,020,233,000 21,828,250,000 22,353,642,000 23,128,514,000 20,748,979,000 19,827,502,000 15,438,707,000 14,273,917,000 10,400,090,000 13,617,068,000 12,406,186,000 12,483,244,000 12,930,398,000 12,784,686,000 11,192,604,000 10,428,809,000 9,626,917,000 12,346,577,000 14,709,661,000 12,722,871,000 14,575,995,000 14,048,927,000 13,318,079,000 13,326,719,000 12,544,941,000 10,689,873,000 10,339,635,000 10,171,883,258 7,815,338,000 7,641,549,000 6,587,329,000 7,169,265,705 8,446,050,000 8,230,013,000 7,729,427,000']

In [204]:
sthdls_eqt_data = gets["Stockholders' Equity"]
sthdls_eqt_data_splt = sthdls_eqt_data.split("\/")
sthdls_eqt_data_splt

['254,915,472,000 255,403,450,000 249,892,661,000 245,499,809,000 240,068,993,000 234,476,380,000 225,671,417,000 215,884,505,000 207,213,416,000 203,504,410,000 193,654,461,000 183,119,607,000 186,424,328,000 173,269,659,000 175,638,353,000 172,130,138,000 172,876,767,000 174,394,863,000 167,808,559,000 161,595,949,000 162,181,725,000 157,717,152,000 153,818,770,000 149,881,253,000 144,442,616,000 139,198,886,000 133,246,470,000 124,136,879,000 117,094,052,000 112,304,233,000 107,789,475,000 103,097,087,000 97,480,294,483 94,372,069,000 90,628,913,000 87,302,752,000 85,470,091,898']

In [205]:
tt_lbt_data = gets["Total Liabilities Net Minority Interest"]
tt_lbt_data_splt = tt_lbt_data.split("\/")
tt_lbt_data_splt

['89,684,076,000 89,943,741,000 85,193,101,000 91,852,732,000 91,604,067,000 95,092,626,000 85,563,535,000 89,213,233,000 87,260,662,000 85,887,328,000 76,883,688,000 74,399,417,000 69,211,291,000 64,935,077,000 62,118,157,000 62,913,603,000 63,119,716,000 65,838,937,000 57,754,240,000 59,631,070,000 62,334,770,000 68,278,794,000 65,209,610,000 69,730,872,000 64,059,008,000 66,374,078,000 65,382,074,000 62,037,027,000 59,591,364,000 60,188,312,000 56,035,900,000 54,649,928,000 53,785,931,529 49,501,637,000 43,361,485,000 45,033,401,000 44,939,652,557']

In [206]:
cmn_stck_data = gets["Common Stock"]
cmn_stck_data_splt = cmn_stck_data.split("\/")
cmn_stck_data_splt

['778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,000 778,047,468 778,047,000 778,047,000 778,047,000 778,047,328']

In [215]:
oprt_cf_data = gets["Operating Cash Flow"]
oprt_cf_data_splt = oprt_cf_data.split("\/")
oprt_cf_data_splt

['45,382,915,000 19,717,140,000 13,826,599,000 6,594,865,000 5,244,311,000 22,428,080,000 15,549,657,000 13,437,774,000 15,616,352,000 21,691,546,000 17,447,062,000 12,426,162,000 10,597,271,000 10,985,912,000 14,336,597,000 13,344,845,000 8,718,290,000 12,356,351,000 11,873,815,000 10,709,603,000 5,121,992,000 5,405,589,000 10,442,348,000 8,914,556,000 12,212,896,000 10,275,299,000 15,014,197,000 8,598,595,000 12,819,349,000 12,074,303,000 11,539,742,000 5,931,820,000 8,426,944,000 7,305,216,994 6,686,653,000 4,567,596,000 4,343,711,000 7,517,122,182 6,757,339,000 3,820,275,000 5,226,417,000']

In [174]:
import pandas as pd
from pandas import DataFrame as pf
import numpy as np

In [235]:
df=pd.Dataframe(gets)
df

AttributeError: module 'pandas' has no attribute 'Dataframe'